#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c thec<tab>/bo<tab>
#
# ...to quickly jump into thecodesmith/boom, for example.

if [ -z "$1" ]; then
    # No argument provided, default to jamf directory
    pushd "$PROJECTS/github/jamf"
elif [ -s "$PROJECTS/github/jamf/$1" ]; then
    # Argument provided and exists in jamf directory
    pushd "$PROJECTS/github/jamf/$1"
else
    # Argument provided, try general projects directory
    pushd "$PROJECTS/$1"
fi
