#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c thec<tab>/bo<tab>
#
# ...to quickly jump into thecodesmith/boom, for example.

if [ ! -z "$1" ] && [ -s "$PROJECTS/github/jamf/$1" ]; then
    pushd "$PROJECTS/github/jamf/$1"
else
    pushd "$PROJECTS/$1"
fi
