#!/bin/sh

enable-pair() {

    if [ $# -ne 1 ]
    then
        echo 'Usage: enable-pair <github username>'
        exit 1
    fi

    # Create an account alias
    sudo dscl . -append /Users/$USER RecordName Pair pair

    # Configure sshd to only allow public-key authentication
    sudo sed -E -i.bak 's/^#?(PasswordAuthentication|ChallengeResponseAuthentication).*$/\1 no/' /etc/ssh/sshd_config

    # Add pair user public key(s)
    touch ~/.ssh/authorized_keys
    gh-auth add --users "$1" --command="$( which tmux ) attach -t pair"
}
