#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# install ssh first so keys and config are available
if [ -f ssh/install.sh ]; then
    bash -c ssh/install.sh
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do bash -c "${installer}" ; done
